name: Rust

on:
  push:
    branches: [ "main" ]
    paths:
      - "00.ray-tracing-in-one-weekend/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    working-directory: 00.ray-tracing-in-one-weekend
    steps:
    - uses: actions/checkout@v3
    - name: Move to ray tracer folder
      run: cd "00.ray-tracing-in-one-weekend"
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
